### ISSUE TITLE
Show when a file is being uploaded

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#64] opened 2021-03-07 20:56 UTC
Sometimes when I send a picture and I see nothing happening, I think the file has been somehow lost, while it's just being uploaded. In this case I think it would help to show a kind of animation

**Comment by BreeceW** [comment] 2021-03-07 20:57
Duplicate of #3

**Comment by MarcAnt01** [comment] 2021-03-07 20:58
Sorry 🤦

**Closed by BreeceW** 2021-03-07 20:57 UTC
